version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api